### ISSUE TITLE
AMI not found

### ISSUE THREAD

**Issue by sk0427** [sanderslab/WGS-pipeline#1]
Unfortunately, I could not find your AMI.

AMI ID
```
ami-1eefb064
```

AMI name
```
Werling 2018 to share
```

Is valid now?

**Comment by gilsonm** [comment]
Greetings, sk0427!

I'm sorry you are having trouble launching the AMI.
Can you help me troubleshoot the problem for you?

If you're searching the AMI in the console, can you verify that you have selected "Public Images" in the search bar rather than "Owned by me"?

If you're trying to launch an EC2 instance through the console, on Step 1., can you verify that you've searched in "Community AMIs"?

-Mike

**Comment by sk0427** [comment]
Thank you Mike.
I re-checked your points but I confirmed that I could not find your AMI in Public Images and Community AMI. Attached is my screenshot. I have some experience on launching EC2 instances however, I am not familiar with launching community AMI.  I am really interested in your pipeline and hope to try it.

Thanks

Satoshi

![comm](https://user-images.githubusercontent.com/33798918/39659747-6c19c52e-506a-11e8-9ca1-9a59bae8aa6a.png)

![amis](https://user-images.githubusercontent.com/33798918/39659749-7ee8529c-506a-11e8-9611-1393d9463c93.png)

**Comment by gilsonm** [comment]
Yikes! This is a tricky one!

I verified that it is public, and was able to search it and launch an instance from it using a different account.

Not sure if region is an issue, but we’re in us-east-1, N. Virginia.

I’ll look into this more thoroughly tomorrow. And if we can’t make progress I’ll get in touch with our AWS rep.

Thanks,
Mike

**Comment by stephansanders** [comment]
Thanks Mike!

S

**Comment by sk0427** [comment]
The region was a big hint.
I changed my region to N. Virginia, then I finally found it!

I am grateful for your speedy response.
Many thanks.

Satoshi

**Comment by gilsonm** [comment]
Fantastic! 
So glad it worked,
Mike
